### ISSUE TITLE
AnythingType produces a nil spec

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/flanders#22]
when we use `flanders.utils/replace-either-with-any` what happens is that it replaces all conditionals/either with AnythingType as expected.
with Schema `AnythingType` translates to `Any`, with spec it should use `any?`.
However the spec part also has gen support, the part that treats AnythingType looks like this:

```clojure
 AnythingType
 (->spec' [{:keys [gen spec]} _ _]
   (with-gen
     (or spec
         any?)
     gen))
```

but the others look like that:

```clojure
InstType
 (->spec' [{:keys [spec] :as node} _ _]
   (with-gen node
     (or spec
         inst?)))
```

so AnythingType returns gen which takes its data from some destructuring from `node`like this:

```clojure
(defn with-gen
 "Used like clojure.spec/with-gen, except that it takes a node (that
 may have :_gen set) and a spec.  If set, :_gen must be a function
 of zero args that returns a generator."
 [{gen :_gen} spec]
 (if gen
   (s/with-gen spec gen)
   spec))
```
here the argument passed to with-gen is gen and not spec and that produces `nil` in the end,
which finally outputs a NPE when used with cs/valid?

**Comment by hshahman** [comment]
No QA required.
